import Data.List
import Data.Char (toUpper, isDigit)
import Data.Maybe (mapMaybe, fromJust)
import Data.Ord (comparing, Down (..))
import Data.Tuple (swap)

main :: IO ()
main = do
  print (sort [3, 1, 4, 1, 5, 9, 2, 6])
  print (sortBy (comparing Down) [3, 1, 4, 1, 5])
  print (sortOn negate [3, 1, 4])
  print (nub [1, 2, 1, 3, 2])
  print ([1, 2, 3, 4] \\ [2, 4])
  print (union [1, 2, 3] [3, 4, 5], intersect [1, 2, 3, 4] [2, 4, 6])
  print (group [1, 1, 2, 3, 3, 3])
  print (partition even [1 .. 8])
  print (find (> 3) [1 .. 9], findIndex (> 3) [1 .. 9], elemIndex 'c' "abcd")
  print (isPrefixOf "ab" "abc", isSuffixOf "bc" "abc", isInfixOf "bc" "abcd")
  print (transpose [[1, 2, 3], [4, 5, 6]])
  print (intercalate ", " ["a", "b", "c"])
  print (intersperse 0 [1, 2, 3])
  print (subsequences [1, 2, 3])
  print (permutations [1, 2, 3])
  print (zip3 [1, 2] "ab" [True, False])
  print (scanl (+) 0 [1, 2, 3], scanl1 (+) [1, 2, 3])
  print (scanr (+) 0 [1, 2, 3], scanr1 (+) [1, 2, 3])
  print (tails [1, 2, 3], inits [1, 2, 3])
  print (maximumBy (comparing snd) [(1, 'a'), (2, 'z'), (3, 'm')])
  print (insert 3 [1, 2, 4, 5])
  print (map toUpper "hello", filter isDigit "a1b2")
  print (mapMaybe (\x -> if even x then Just (x * 10) else Nothing) [1 .. 6])
  print (fromJust (Just 7), swap (1, 'x'))
  print (foldl' (+) 0 [1 .. 100], genericLength "abcd")
  print (Data.List.lookup 'b' (zip "abc" [1 .. 3 :: Integer]))
