-- Generates runtime/ahc_unicode.h from GHC's OWN Data.Char, so
-- AHC's Unicode classification and simple case mappings agree with
-- the conformance oracle by construction (not by chasing a Unicode
-- version). Regenerate when the oracle GHC changes:
--
--   runghc tests/gen_unicode.hs > runtime/ahc_unicode.h
--
-- Layout: a two-level table over code points 0..10FFFF. Each 256-
-- point page is one of a deduplicated set of 256-byte pages; the
-- page index is uint16. Each byte is a bitmask of the six
-- table-driven predicates (digit/hex/oct stay ASCII, as in GHC).
-- Case mappings are (start, length, delta) runs over the simple
-- single-char mappings (multi-char full mappings map to identity,
-- matching GHC's toUpper/toLower).
import Data.Char
import Data.List (intercalate)
import qualified Data.Map as Map

bitmask :: Char -> Int
bitmask c =
  sum [ b | (b, p) <- [ (1, isUpper), (2, isLower), (4, isAlpha)
                      , (8, isAlphaNum), (16, isPunctuation)
                      , (32, isSpace) ]
          , p c ]

pages :: [[Int]]
pages = [ [ bitmask (toEnum (pg * 256 + i)) | i <- [0 .. 255] ]
        | pg <- [0 .. 0x10FF] ]

-- (unique pages in first-seen order, per-page index)
dedup :: ([[Int]], [Int])
dedup = go Map.empty [] [] pages
  where
    go _ acc idx [] = (reverse acc, reverse idx)
    go seen acc idx (p : ps) =
      case Map.lookup p seen of
        Just i -> go seen acc (i : idx) ps
        Nothing ->
          let i = Map.size seen
          in go (Map.insert p i seen) (p : acc) (i : idx) ps

-- Simple case-map runs: consecutive code points sharing one delta.
runs :: (Char -> Char) -> [(Int, Int, Int)]
runs f = merge [ (c, d) | c <- [0 .. 0x10FFFF]
               , let d = delta c, d /= 0 ]
  where
    delta c =
      let ch = toEnum c
          m = f ch
      in fromEnum m - c
    merge [] = []
    merge ((c0, d0) : rest) = go c0 1 d0 rest
      where
        go s n d ((c, d') : xs)
          | c == s + n && d' == d = go s (n + 1) d xs
          | otherwise = (s, n, d) : go c 1 d' xs
        go s n d [] = [(s, n, d)]

emitBytes :: [Int] -> String
emitBytes = intercalate "," . map show

main :: IO ()
main = do
  let (uniq, idx) = dedup
  putStrLn "/* Generated by tests/gen_unicode.hs from the oracle"
  putStrLn "   GHC's Data.Char - DO NOT EDIT. Regenerate with:"
  putStrLn "   runghc tests/gen_unicode.hs > runtime/ahc_unicode.h"
  putStrLn "   Bits: 1 upper, 2 lower, 4 alpha, 8 alphanum,"
  putStrLn "   16 punctuation, 32 space. */"
  putStrLn "typedef struct { int32_t s; int32_t n; int32_t d; }"
  putStrLn "  AhcUcRun;"
  putStrLn ("static const uint8_t ahc_uc_pages["
            ++ show (length uniq) ++ "][256] = {")
  mapM_ (\p -> putStrLn ("  {" ++ emitBytes p ++ "},")) uniq
  putStrLn "};"
  putStrLn ("static const uint16_t ahc_uc_index["
            ++ show (length idx) ++ "] = {")
  putStrLn ("  " ++ emitBytes idx)
  putStrLn "};"
  let up = runs toUpper
      lo = runs toLower
      emitRuns name rs = do
        putStrLn ("static const AhcUcRun " ++ name ++ "["
                  ++ show (length rs) ++ "] = {")
        mapM_ (\(s, n, d) -> putStrLn ("  {" ++ show s ++ ","
                                       ++ show n ++ "," ++ show d
                                       ++ "},")) rs
        putStrLn "};"
  emitRuns "ahc_uc_upper" up
  emitRuns "ahc_uc_lower" lo
