#!/usr/bin/env python3
"""Regenerate src/ahc-report_prelude.adb: the names GHC 9.4.8's Prelude
exports (values, types/classes, constructors), from `:browse Prelude`.

AHC's Prelude is wider than GHC's (fromMaybe, swap, internal helpers),
so M144's own-declaration-vs-Prelude ambiguity must only fire for names
GHC's Prelude actually exports.   usage: scripts/gen_report_prelude.py
"""
import re, subprocess, os
ghc = os.path.expanduser("~/.ghcup/bin/ghc")
out = subprocess.run([ghc, "-e", ":browse Prelude"], capture_output=True,
                     text=True, check=True).stdout
vals, types, cons = set(), set(), set()
for l in out.split("\n"):
    if l.startswith("type ") and "::" in l:
        continue
    m = re.match(r"^(class|data|newtype|type)\s+(.*)$", l)
    if m:
        kind, rest = m.groups()
        if kind == "class":
            rest = rest.split(" where")[0]
            if "=>" in rest:
                rest = rest.split("=>")[-1]
            types.add(rest.split()[0])
        else:
            types.add(rest.split("=")[0].split()[0])
            if "=" in rest and kind in ("data", "newtype"):
                for alt in rest.split("=", 1)[1].split("|"):
                    t = alt.strip().split()
                    if t and "." not in t[0] and "#" not in t[0]:
                        cons.add(t[0])
        continue
    m = re.match(r"^\s*(\(?[^\s]+?\)?) ::", l)
    if m:
        n = m.group(1)
        if re.match(r"^(\w+\.)+\w", n.strip("()")) and not n.startswith("("):
            continue                      # a qualified, unexported method
        vals.add(n.strip("()"))
types.discard("(~)")
rows = ([("V", v) for v in sorted(vals)] + [("T", t) for t in sorted(types)]
        + [("C", c) for c in sorted(cons)])
open(os.path.join(os.path.dirname(__file__), "..", "src",
                  "ahc-report_prelude.adb"), "w").write(f"""--  GENERATED by scripts/gen_report_prelude.py from GHC 9.4.8's
--  `:browse Prelude` - do not edit.
with Ada.Containers.Indefinite_Hashed_Sets;
with Ada.Strings.Hash;

package body AHC.Report_Prelude is

   package String_Sets is new Ada.Containers.Indefinite_Hashed_Sets
     (String, Ada.Strings.Hash, "=");

   Names : String_Sets.Set;
   Ready : Boolean := False;

   Table : constant array (Positive range <>) of access String :=
     [{(",\n      ").join(f'new String\'("{k}{n}")' for k, n in rows)}];

   function Exports (Kind : Character; Name : String) return Boolean is
   begin
      if not Ready then
         for T of Table loop
            Names.Include (T.all);
         end loop;
         Ready := True;
      end if;
      return Names.Contains (Kind & Name);
   end Exports;

end AHC.Report_Prelude;
""")
print(len(rows), "names")
