package body AHC.Bindgen is

   use AHC.Core;
   use Ada.Strings.Unbounded;

   LF : constant Character := ASCII.LF;

   function Supported (Lang : String) return Boolean
   is (Lang in "cpp" | "rust" | "go" | "ghc");

   function File_Name (Lang : String) return String
   is (if Lang = "cpp" then "ahc_exports.hpp"
       elsif Lang = "rust" then "ahc_exports.rs"
       elsif Lang = "go" then "ahc.go"
       else "AhcLib.hs");

   function Generate
     (Lang    : String;
      Lib     : String;
      Exports : Core.Foreign_Vectors.Vector;
      Table   : Names.Name_Table)
      return Ada.Strings.Unbounded.Unbounded_String
   is
      R : Unbounded_String;

      function CN (F : Foreign_Import) return String
      is (Table.Text (Names.Real_Name_Id (F.C_Name)));

      --  Shared fixed-width spellings (identical in C++ and cgo).
      function Fix_C (K : Fixed_Marshal) return String
      is (case K is
            when M_I8 => "int8_t",   when M_I16 => "int16_t",
            when M_I32 => "int32_t", when M_I64 => "int64_t",
            when M_U8 => "uint8_t",  when M_U16 => "uint16_t",
            when M_U32 => "uint32_t", when M_U64 => "uint64_t");

      ------------------------------------------------------------------
      --  C++: an RAII class over ahc_exports.h
      ------------------------------------------------------------------

      procedure Gen_Cpp is

         function T (K : Marshal_Kind; Ret : Boolean) return String
         is (case K is
               when M_Int | M_Char => "long",
               when M_Double => "double",
               when M_Bool => "bool",
               when M_Unit => "void",
               when M_String =>
                 (if Ret then "std::string"
                  else "const std::string &"),
               when M_Ptr => "void *",
               when Fixed_Marshal => Fix_C (K));

      begin
         Append (R,
           "// Generated by ahc bindgen - C++ wrapper over " & Lib
           & "." & LF
           & "// Link " & Lib & " (and the collector, e.g. -lgc)."
           & LF
           & "// One Lib per process; construct it on the one thread"
           & LF
           & "// that will make all calls. Runtime errors inside the"
           & LF
           & "// library surface as std::runtime_error." & LF
           & "#pragma once" & LF
           & "#include <cstdint>" & LF
           & "#include <cstdlib>" & LF
           & "#include <stdexcept>" & LF
           & "#include <string>" & LF
           & "#include ""ahc_exports.h""" & LF & LF
           & "namespace ahc {" & LF
           & "class Lib {" & LF
           & "  static void check_() {" & LF
           & "    if (*ahc_last_error())" & LF
           & "      throw std::runtime_error(ahc_last_error());" & LF
           & "  }" & LF & LF
           & "public:" & LF
           & "  Lib() { ahc_lib_init(); }" & LF
           & "  Lib(const Lib &) = delete;" & LF
           & "  Lib &operator=(const Lib &) = delete;" & LF & LF);
         for F of Exports loop
            declare
               N : constant Natural := Natural (F.Args.Length);
               Call : Unbounded_String;
            begin
               Append (R, "  " & T (F.Res, True) & " " & CN (F)
                       & "(");
               for I in 1 .. N loop
                  Append (R, (if I > 1 then ", " else "")
                          & T (F.Args (I), False) & " a"
                          & Integer'Image (I - 1)
                              (2 .. Integer'Image (I - 1)'Length));
               end loop;
               Append (R, ") {" & LF);
               Append (Call, "::" & CN (F) & "(");
               for I in 1 .. N loop
                  declare
                     A : constant String :=
                       "a" & Integer'Image (I - 1)
                               (2 .. Integer'Image (I - 1)'Length);
                  begin
                     Append (Call, (if I > 1 then ", " else "")
                             & (case F.Args (I) is
                                  when M_Bool => A & " ? 1 : 0",
                                  when M_String => A & ".c_str()",
                                  when others => A));
                  end;
               end loop;
               Append (Call, ")");
               case F.Res is
                  when M_Unit =>
                     Append (R, "    " & Call & ";" & LF
                             & "    check_();" & LF);
                  when M_Bool =>
                     Append (R, "    int r_ = " & Call & ";" & LF
                             & "    check_();" & LF
                             & "    return r_ != 0;" & LF);
                  when M_String =>
                     Append (R, "    char *r_ = " & Call & ";" & LF
                             & "    check_();" & LF
                             & "    std::string s_(r_);" & LF
                             & "    std::free(r_);" & LF
                             & "    return s_;" & LF);
                  when others =>
                     Append (R, "    " & T (F.Res, True) & " r_ = "
                             & Call & ";" & LF
                             & "    check_();" & LF
                             & "    return r_;" & LF);
               end case;
               Append (R, "  }" & LF & LF);
            end;
         end loop;
         Append (R, "};" & LF & "}  // namespace ahc" & LF);
      end Gen_Cpp;

      ------------------------------------------------------------------
      --  Rust: raw extern block + safe wrappers, one file consumed
      --  as `mod ahc_exports;`
      ------------------------------------------------------------------

      procedure Gen_Rust is

         function Raw (K : Marshal_Kind; Ret : Boolean) return String
         is (case K is
               when M_Int | M_Char => "c_long",
               when M_Double => "f64",
               when M_Bool => "c_int",
               when M_Unit => "()",
               when M_String =>
                 (if Ret then "*mut c_char" else "*const c_char"),
               when M_Ptr => "*mut c_void",
               when M_I8 => "i8",   when M_I16 => "i16",
               when M_I32 => "i32", when M_I64 => "i64",
               when M_U8 => "u8",   when M_U16 => "u16",
               when M_U32 => "u32", when M_U64 => "u64");

         function Pub (K : Marshal_Kind) return String
         is (case K is
               when M_Int | M_Char => "i64",
               when M_Double => "f64",
               when M_Bool => "bool",
               when M_Unit => "()",
               when M_String => "String",
               when M_Ptr => "*mut c_void",
               when others => Raw (K, False));

         function Arg (I : Natural) return String
         is ("a" & Integer'Image (I) (2 .. Integer'Image (I)'Length));

      begin
         Append (R,
           "// Generated by ahc bindgen - safe Rust wrappers over "
           & Lib & "." & LF
           & "// Consume as `mod ahc_exports;`, link " & Lib
           & " and the collector:" & LF
           & "//   rustc main.rs -C link-arg=" & Lib
           & " -C link-arg=-lgc" & LF
           & "// Call init() once, from the one thread that makes"
           & " all calls." & LF
           & "// Runtime errors inside the library surface as"
           & " Err(String)." & LF
           & "#![allow(dead_code)]" & LF
           & "#![allow(unused_imports)]" & LF
           & "#![allow(non_snake_case)]" & LF & LF
           & "use std::ffi::{CStr, CString};" & LF
           & "use std::os::raw::{c_char, c_int, c_long, c_void};"
           & LF & LF
           & "mod raw {" & LF
           & "    use super::*;" & LF
           & "    extern ""C"" {" & LF
           & "        pub fn ahc_lib_init();" & LF
           & "        pub fn ahc_last_error() -> *const c_char;" & LF
           & "        pub fn free(p: *mut c_void);" & LF);
         for F of Exports loop
            declare
               N : constant Natural := Natural (F.Args.Length);
            begin
               Append (R, "        pub fn " & CN (F) & "(");
               for I in 1 .. N loop
                  Append (R, (if I > 1 then ", " else "")
                          & Arg (I - 1) & ": "
                          & Raw (F.Args (I), False));
               end loop;
               Append (R, ")");
               if F.Res /= M_Unit then
                  Append (R, " -> " & Raw (F.Res, True));
               end if;
               Append (R, ";" & LF);
            end;
         end loop;
         Append (R, "    }" & LF & "}" & LF & LF
                 & "pub fn init() { unsafe { raw::ahc_lib_init() } }"
                 & LF & LF
                 & "fn err_check() -> Result<(), String> {" & LF
                 & "    unsafe {" & LF
                 & "        let e = raw::ahc_last_error();" & LF
                 & "        if *e == 0 {" & LF
                 & "            Ok(())" & LF
                 & "        } else {" & LF
                 & "            Err(CStr::from_ptr(e)"
                 & ".to_string_lossy().into_owned())" & LF
                 & "        }" & LF
                 & "    }" & LF
                 & "}" & LF & LF);
         for F of Exports loop
            declare
               N : constant Natural := Natural (F.Args.Length);
               Call : Unbounded_String;
            begin
               Append (R, "pub fn " & CN (F) & "(");
               for I in 1 .. N loop
                  Append (R, (if I > 1 then ", " else "")
                          & Arg (I - 1) & ": "
                          & (if F.Args (I) = M_String then "&str"
                             else Pub (F.Args (I))));
               end loop;
               Append (R, ") -> Result<" & Pub (F.Res)
                       & ", String> {" & LF);
               for I in 1 .. N loop
                  if F.Args (I) = M_String then
                     Append (R, "    let " & Arg (I - 1)
                             & "_c = CString::new(" & Arg (I - 1)
                             & ").map_err(|_| ""interior NUL"""
                             & ".to_string())?;" & LF);
                  end if;
               end loop;
               Append (Call, "raw::" & CN (F) & "(");
               for I in 1 .. N loop
                  Append (Call, (if I > 1 then ", " else "")
                          & (case F.Args (I) is
                               when M_Int | M_Char =>
                                 Arg (I - 1) & " as c_long",
                               when M_Bool =>
                                 "if " & Arg (I - 1)
                                 & " { 1 } else { 0 }",
                               when M_String =>
                                 Arg (I - 1) & "_c.as_ptr()",
                               when others => Arg (I - 1)));
               end loop;
               Append (Call, ")");
               Append (R, "    unsafe {" & LF);
               case F.Res is
                  when M_Unit =>
                     Append (R, "        " & Call & ";" & LF
                             & "        err_check()?;" & LF
                             & "        Ok(())" & LF);
                  when M_Bool =>
                     Append (R, "        let r_ = " & Call & ";" & LF
                             & "        err_check()?;" & LF
                             & "        Ok(r_ != 0)" & LF);
                  when M_Int | M_Char =>
                     Append (R, "        let r_ = " & Call & ";" & LF
                             & "        err_check()?;" & LF
                             & "        Ok(r_ as i64)" & LF);
                  when M_String =>
                     Append (R, "        let r_ = " & Call & ";" & LF
                             & "        err_check()?;" & LF
                             & "        let s_ = CStr::from_ptr(r_)"
                             & ".to_string_lossy().into_owned();"
                             & LF
                             & "        raw::free(r_ as *mut "
                             & "c_void);" & LF
                             & "        Ok(s_)" & LF);
                  when others =>
                     Append (R, "        let r_ = " & Call & ";" & LF
                             & "        err_check()?;" & LF
                             & "        Ok(r_)" & LF);
               end case;
               Append (R, "    }" & LF & "}" & LF & LF);
            end;
         end loop;
      end Gen_Rust;

      ------------------------------------------------------------------
      --  Go: a cgo package that funnels every call to one locked
      --  OS thread, so any goroutine may use the wrappers.
      ------------------------------------------------------------------

      procedure Gen_Go is

         function Pub (K : Marshal_Kind) return String
         is (case K is
               when M_Int | M_Char => "int64",
               when M_Double => "float64",
               when M_Bool => "bool",
               when M_Unit => "",
               when M_String => "string",
               when M_Ptr => "unsafe.Pointer",
               when M_I8 => "int8",   when M_I16 => "int16",
               when M_I32 => "int32", when M_I64 => "int64",
               when M_U8 => "uint8",  when M_U16 => "uint16",
               when M_U32 => "uint32", when M_U64 => "uint64");

         function C_Cast (K : Marshal_Kind; A : String)
            return String
         is (case K is
               when M_Int | M_Char => "C.long(" & A & ")",
               when M_Double => "C.double(" & A & ")",
               when M_Bool => "b2c(" & A & ")",
               when M_String => A & "_c",
               when M_Ptr => A,
               when Fixed_Marshal =>
                 "C." & Fix_C (K) & "(" & A & ")",
               when M_Unit => A);

         function Arg (I : Natural) return String
         is ("a" & Integer'Image (I) (2 .. Integer'Image (I)'Length));

         function Go_Name (S : String) return String is
            U : String := S;
         begin
            if U (U'First) in 'a' .. 'z' then
               U (U'First) := Character'Val
                 (Character'Pos (U (U'First)) - 32);
            end if;
            return U;
         end Go_Name;

      begin
         Append (R,
           "// Code generated by ahc bindgen - cgo wrappers over "
           & Lib & "." & LF
           & "// The AHC runtime is single-threaded: every call is"
           & " funneled to one" & LF
           & "// locked OS thread, so any goroutine may call these"
           & " wrappers." & LF
           & "// Add collector link flags via CGO_LDFLAGS (e.g."
           & " -L<gc>/lib -lgc)." & LF
           & "package ahc" & LF & LF
           & "/*" & LF
           & "#cgo LDFLAGS: ${SRCDIR}/" & Lib & LF
           & "#include <stdint.h>" & LF
           & "#include <stdlib.h>" & LF
           & "#include ""ahc_exports.h""" & LF
           & "*/" & LF
           & "import ""C""" & LF & LF
           & "import (" & LF
           & "        ""errors""" & LF
           & "        ""runtime""" & LF
           & "        ""unsafe""" & LF
           & ")" & LF & LF
           & "var _ = unsafe.Pointer(nil)" & LF & LF
           & "func lastErr() error {" & LF
           & "        s := C.GoString(C.ahc_last_error())" & LF
           & "        if s == """" {" & LF
           & "                return nil" & LF
           & "        }" & LF
           & "        return errors.New(s)" & LF
           & "}" & LF & LF
           & "var reqs = make(chan func())" & LF & LF
           & "func init() {" & LF
           & "        ready := make(chan struct{})" & LF
           & "        go func() {" & LF
           & "                runtime.LockOSThread()" & LF
           & "                C.ahc_lib_init()" & LF
           & "                close(ready)" & LF
           & "                for f := range reqs {" & LF
           & "                        f()" & LF
           & "                }" & LF
           & "        }()" & LF
           & "        <-ready" & LF
           & "}" & LF & LF
           & "func do(f func()) {" & LF
           & "        done := make(chan struct{})" & LF
           & "        reqs <- func() { f(); close(done) }" & LF
           & "        <-done" & LF
           & "}" & LF & LF
           & "func b2c(b bool) C.int {" & LF
           & "        if b {" & LF
           & "                return 1" & LF
           & "        }" & LF
           & "        return 0" & LF
           & "}" & LF & LF
           & "var _ = b2c" & LF & LF);
         for F of Exports loop
            declare
               N : constant Natural := Natural (F.Args.Length);
               Call : Unbounded_String;
            begin
               Append (R, "func " & Go_Name (CN (F)) & "(");
               for I in 1 .. N loop
                  Append (R, (if I > 1 then ", " else "")
                          & Arg (I - 1) & " " & Pub (F.Args (I)));
               end loop;
               if F.Res = M_Unit then
                  Append (R, ") error {" & LF);
               else
                  Append (R, ") (" & Pub (F.Res) & ", error) {"
                          & LF);
               end if;
               if F.Res /= M_Unit then
                  Append (R, "        var r " & Pub (F.Res) & LF);
               end if;
               Append (R, "        var e error" & LF);
               Append (R, "        do(func() {" & LF);
               for I in 1 .. N loop
                  if F.Args (I) = M_String then
                     Append (R, "                " & Arg (I - 1)
                             & "_c := C.CString(" & Arg (I - 1)
                             & ")" & LF);
                  end if;
               end loop;
               Append (Call, "C." & CN (F) & "(");
               for I in 1 .. N loop
                  Append (Call, (if I > 1 then ", " else "")
                          & C_Cast (F.Args (I), Arg (I - 1)));
               end loop;
               Append (Call, ")");
               case F.Res is
                  when M_Unit =>
                     Append (R, "                " & Call & LF
                             & "                e = lastErr()" & LF);
                  when M_Bool =>
                     Append (R, "                r_ := " & Call & LF
                             & "                e = lastErr()" & LF
                             & "                r = r_ != 0" & LF);
                  when M_String =>
                     Append (R, "                p_ := " & Call & LF
                             & "                e = lastErr()" & LF
                             & "                if e == nil {" & LF
                             & "                        r = "
                             & "C.GoString(p_)" & LF
                             & "                        C.free("
                             & "unsafe.Pointer(p_))" & LF
                             & "                }" & LF);
                  when M_Ptr =>
                     Append (R, "                r = " & Call & LF
                             & "                e = lastErr()" & LF);
                  when others =>
                     Append (R, "                r = " & Pub (F.Res)
                             & "(" & Call & ")" & LF
                             & "                e = lastErr()" & LF);
               end case;
               for I in 1 .. N loop
                  if F.Args (I) = M_String then
                     Append (R, "                C.free(unsafe.Pointer("
                             & Arg (I - 1) & "_c))" & LF);
                  end if;
               end loop;
               Append (R, "        })" & LF);
               if F.Res = M_Unit then
                  Append (R, "        return e" & LF);
               else
                  Append (R, "        return r, e" & LF);
               end if;
               Append (R, "}" & LF & LF);
            end;
         end loop;
      end Gen_Go;

      ------------------------------------------------------------------
      --  GHC: foreign imports over ahc_exports.h; String/Bool get
      --  small marshalling wrappers.
      ------------------------------------------------------------------

      procedure Gen_Ghc is

         function Raw (K : Marshal_Kind) return String
         is (case K is
               when M_Int | M_Char => "CLong",
               when M_Double => "CDouble",
               when M_Bool => "CInt",
               when M_Unit => "()",
               when M_String => "CString",
               when M_Ptr => "Ptr ()",
               when M_I8 => "Int8",   when M_I16 => "Int16",
               when M_I32 => "Int32", when M_I64 => "Int64",
               when M_U8 => "Word8",  when M_U16 => "Word16",
               when M_U32 => "Word32", when M_U64 => "Word64");

         function Arg (I : Natural) return String
         is ("a" & Integer'Image (I) (2 .. Integer'Image (I)'Length));

      begin
         Append (R,
           "-- Generated by ahc bindgen - GHC bindings over " & Lib
           & "." & LF
           & "-- Build: ghc Main.hs AhcLib.hs " & Lib
           & " -lgc (with the collector's -L path)." & LF
           & "-- Call ahcLibInit once, from the one thread that"
           & " makes all calls." & LF
           & "-- Runtime errors inside the library surface as"
           & " IOError (userError)." & LF
           & "{-# LANGUAGE ForeignFunctionInterface #-}" & LF
           & "module AhcLib where" & LF & LF
           & "import Data.Int" & LF
           & "import Data.Word" & LF
           & "import Foreign.C.String" & LF
           & "import Foreign.C.Types" & LF
           & "import Foreign.Marshal.Alloc (free)" & LF
           & "import Foreign.Ptr" & LF & LF
           & "foreign import ccall ""ahc_lib_init"" ahcLibInit"
           & " :: IO ()" & LF & LF
           & "foreign import ccall ""ahc_last_error"""
           & " c_ahcLastError :: IO CString" & LF & LF
           & "ahcCheck :: IO ()" & LF
           & "ahcCheck = do" & LF
           & "  e <- c_ahcLastError" & LF
           & "  s <- peekCString e" & LF
           & "  if null s then return ()"
           & " else ioError (userError s)" & LF & LF);
         for F of Exports loop
            declare
               N : constant Natural := Natural (F.Args.Length);
               Raw_Name : constant String := "c_" & CN (F);
            begin
               Append (R, "foreign import ccall """ & CN (F)
                       & """ " & Raw_Name & LF & "  :: ");
               for I in 1 .. N loop
                  Append (R, Raw (F.Args (I)) & " -> ");
               end loop;
               Append (R, "IO (" & Raw (F.Res) & ")" & LF);
               Append (R, CN (F) & " :: ");
               for I in 1 .. N loop
                  Append (R,
                          (case F.Args (I) is
                             when M_String => "String",
                             when M_Bool => "Bool",
                             when others => Raw (F.Args (I)))
                          & " -> ");
               end loop;
               Append (R, "IO ("
                       & (case F.Res is
                            when M_String => "String",
                            when M_Bool => "Bool",
                            when others => Raw (F.Res))
                       & ")" & LF);
               Append (R, CN (F));
               for I in 1 .. N loop
                  Append (R, " " & Arg (I - 1));
               end loop;
               Append (R, " =" & LF);
               declare
                  Ind : Unbounded_String :=
                    To_Unbounded_String ("  ");
                  Call : Unbounded_String;
               begin
                  for I in 1 .. N loop
                     if F.Args (I) = M_String then
                        Append (R, Ind & "withCString "
                                & Arg (I - 1) & " (\c"
                                & Arg (I - 1) & " -> " & LF);
                        Append (Ind, "  ");
                     end if;
                  end loop;
                  Append (Call, Raw_Name);
                  for I in 1 .. N loop
                     Append (Call, " "
                             & (case F.Args (I) is
                                  when M_String =>
                                    "c" & Arg (I - 1),
                                  when M_Bool =>
                                    "(if " & Arg (I - 1)
                                    & " then 1 else 0)",
                                  when others => Arg (I - 1)));
                  end loop;
                  Append (R, Ind & "do r_ <- " & Call & LF);
                  Append (R, Ind & "   ahcCheck" & LF);
                  case F.Res is
                     when M_String =>
                        Append (R, Ind & "   s_ <- peekCString"
                                & " r_" & LF
                                & Ind & "   free r_" & LF
                                & Ind & "   return s_");
                     when M_Bool =>
                        Append (R, Ind
                                & "   return (r_ /= 0)");
                     when others =>
                        Append (R, Ind & "   return r_");
                  end case;
                  for I in 1 .. N loop
                     if F.Args (I) = M_String then
                        Append (R, ")");
                     end if;
                  end loop;
                  Append (R, "" & LF);
               end;
               Append (R, "" & LF);
            end;
         end loop;
      end Gen_Ghc;

   begin
      if Lang = "cpp" then
         Gen_Cpp;
      elsif Lang = "rust" then
         Gen_Rust;
      elsif Lang = "go" then
         Gen_Go;
      else
         Gen_Ghc;
      end if;
      return R;
   end Generate;

end AHC.Bindgen;
